#include <stdio.h>

/**
 * main - program entry point
 *
 * Description: Each new term in the Fibonacci sequence is generated by adding
 * the previous two terms. By starting with 1 and 2, the first 10 terms will be
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89. By considering the terms in the Fibonacci
 * sequence whose values do not exceed 4, 000, 000, this program finds and
 * prints the sum of the even-valued terms, followed by a new line.
 * Return: 0 (success)
 */
int main(void)
{
	long num1, num2, fib;
	long sum;

	num1 = 1;
	num2 = 2;
	sum = 2;
	
	do
	{
		fib = num1 + num2;
		num1 = num2;
		num2 = fib;

		if (!(fib % 2) && fib < 4000000)
			sum += fib;
	}
	while (fib < 4000000);

	printf("%ld\n", sum);

	return (0);
}

